create extension if not exists pgcrypto;
create table public.profiles(id uuid primary key references auth.users(id) on delete cascade,first_name text not null,last_name text not null,role text not null default 'student' check(role in('student','teacher')),avatar_url text,created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.groups(id uuid primary key default gen_random_uuid(),name text not null,description text,teacher_id uuid not null references public.profiles(id),created_at timestamptz not null default now(),updated_at timestamptz not null default now());
create table public.group_members(id uuid primary key default gen_random_uuid(),group_id uuid not null references public.groups(id) on delete cascade,student_id uuid not null references public.profiles(id) on delete cascade,created_at timestamptz not null default now(),unique(group_id,student_id));
create table public.schedule_items(id uuid primary key default gen_random_uuid(),group_id uuid not null references public.groups(id) on delete cascade,teacher_id uuid not null references public.profiles(id),title text not null,description text,room text,starts_at timestamptz not null,ends_at timestamptz not null,status text not null default 'scheduled' check(status in('scheduled','changed','cancelled','completed')),created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(ends_at>starts_at));
create table public.chat_rooms(id uuid primary key default gen_random_uuid(),group_id uuid not null unique references public.groups(id) on delete cascade,name text not null,created_by uuid not null references public.profiles(id),created_at timestamptz not null default now());
create table public.messages(id uuid primary key default gen_random_uuid(),chat_room_id uuid not null references public.chat_rooms(id) on delete cascade,sender_id uuid not null references public.profiles(id),content text not null,reply_to_id uuid references public.messages(id) on delete set null,is_deleted boolean not null default false,created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(length(trim(content)) between 1 and 2000));
create index on public.group_members(student_id);create index on public.schedule_items(group_id,starts_at);create index on public.messages(chat_room_id,created_at);

create or replace function public.set_updated_at() returns trigger language plpgsql set search_path='' as $$begin new.updated_at=now();return new;end$$;
create trigger profiles_updated before update on public.profiles for each row execute function public.set_updated_at();create trigger groups_updated before update on public.groups for each row execute function public.set_updated_at();create trigger schedule_updated before update on public.schedule_items for each row execute function public.set_updated_at();create trigger messages_updated before update on public.messages for each row execute function public.set_updated_at();
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path='' as $$begin insert into public.profiles(id,first_name,last_name,role)values(new.id,coalesce(nullif(new.raw_user_meta_data->>'first_name',''),'New'),coalesce(nullif(new.raw_user_meta_data->>'last_name',''),'User'),'student');return new;end$$;
create trigger on_auth_user_created after insert on auth.users for each row execute function public.handle_new_user();
create or replace function public.prevent_role_change() returns trigger language plpgsql set search_path='' as $$begin if new.role<>old.role and auth.uid()=old.id then raise exception 'Users cannot change their own role';end if;return new;end$$;
create trigger prevent_self_role_change before update on public.profiles for each row execute function public.prevent_role_change();

create or replace function public.is_teacher_of(gid uuid) returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.groups where id=gid and teacher_id=auth.uid())$$;
create or replace function public.is_member_of(gid uuid) returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.group_members where group_id=gid and student_id=auth.uid())$$;
create or replace function public.can_access_group(gid uuid) returns boolean language sql stable security definer set search_path='' as $$select public.is_teacher_of(gid) or public.is_member_of(gid)$$;
create or replace function public.can_access_profile(pid uuid) returns boolean language sql stable security definer set search_path='' as $$select pid=auth.uid() or exists(select 1 from public.groups g left join public.group_members mine on mine.group_id=g.id and mine.student_id=auth.uid() left join public.group_members theirs on theirs.group_id=g.id and theirs.student_id=pid where (g.teacher_id=auth.uid() and (pid=g.teacher_id or theirs.student_id is not null)) or (mine.student_id is not null and (pid=g.teacher_id or theirs.student_id is not null))) or exists(select 1 from public.profiles p where p.id=auth.uid() and p.role='teacher' and exists(select 1 from public.profiles t where t.id=pid and t.role='teacher'))$$;

alter table public.profiles enable row level security;alter table public.groups enable row level security;alter table public.group_members enable row level security;alter table public.schedule_items enable row level security;alter table public.chat_rooms enable row level security;alter table public.messages enable row level security;
create policy profiles_read on public.profiles for select to authenticated using(public.can_access_profile(id));create policy profile_self_update on public.profiles for update to authenticated using(id=auth.uid()) with check(id=auth.uid());
create policy groups_read on public.groups for select to authenticated using(public.can_access_group(id));create policy groups_insert on public.groups for insert to authenticated with check(teacher_id=auth.uid());create policy groups_update on public.groups for update to authenticated using(teacher_id=auth.uid()) with check(teacher_id=auth.uid());create policy groups_delete on public.groups for delete to authenticated using(teacher_id=auth.uid());
create policy members_read on public.group_members for select to authenticated using(public.can_access_group(group_id));create policy members_insert on public.group_members for insert to authenticated with check(public.is_teacher_of(group_id) and exists(select 1 from public.profiles where id=student_id and role='student'));create policy members_delete on public.group_members for delete to authenticated using(public.is_teacher_of(group_id));
create policy schedule_read on public.schedule_items for select to authenticated using(public.can_access_group(group_id));create policy schedule_insert on public.schedule_items for insert to authenticated with check(public.is_teacher_of(group_id) and teacher_id=auth.uid());create policy schedule_update on public.schedule_items for update to authenticated using(public.is_teacher_of(group_id)) with check(public.is_teacher_of(group_id) and teacher_id=auth.uid());create policy schedule_delete on public.schedule_items for delete to authenticated using(public.is_teacher_of(group_id));
create policy rooms_read on public.chat_rooms for select to authenticated using(public.can_access_group(group_id));create policy rooms_insert on public.chat_rooms for insert to authenticated with check(public.is_teacher_of(group_id) and created_by=auth.uid());create policy rooms_update on public.chat_rooms for update to authenticated using(public.is_teacher_of(group_id)) with check(public.is_teacher_of(group_id));
create policy messages_read on public.messages for select to authenticated using(exists(select 1 from public.chat_rooms r where r.id=chat_room_id and public.can_access_group(r.group_id)));create policy messages_insert on public.messages for insert to authenticated with check(sender_id=auth.uid() and exists(select 1 from public.chat_rooms r where r.id=chat_room_id and public.can_access_group(r.group_id)));create policy messages_update on public.messages for update to authenticated using(sender_id=auth.uid() or exists(select 1 from public.chat_rooms r where r.id=chat_room_id and public.is_teacher_of(r.group_id))) with check(is_deleted=true and exists(select 1 from public.chat_rooms r where r.id=chat_room_id and public.can_access_group(r.group_id)));
alter publication supabase_realtime add table public.messages;
grant execute on function public.is_teacher_of(uuid),public.is_member_of(uuid),public.can_access_group(uuid),public.can_access_profile(uuid) to authenticated;
